import type { Movie } from "@/lib/types";

/**
 * The Marvel Cinematic Universe theatrical slate, Phase One → Phase Six.
 *
 * `chronoOrder` is 1-based in-universe chronological order (Marvel's own
 * timeline ordering), which the MCU Timeline view can sort by instead of
 * release date.
 */
const STUDIO = "Marvel Studios";

export const MCU_MOVIES: Movie[] = [
  // ── Phase One ──────────────────────────────────────────────────────────────
  {
    id: "iron-man", title: "Iron Man", year: 2008, phase: 1, chronoOrder: 3,
    releaseDate: "2008-05-02", director: "Jon Favreau", runtime: 126,
    synopsis: "A captive weapons magnate builds a powered suit of armour and rebuilds himself with it.",
    initials: "IM", imdbId: "tt0371746", imdbRating: 7.9,
    universe: "mcu", studio: STUDIO, franchise: "Iron Man",
    characters: ["iron-man"], villains: ["Obadiah Stane", "Raza"],
  },
  {
    id: "the-incredible-hulk", title: "The Incredible Hulk", year: 2008, phase: 1, chronoOrder: 5,
    releaseDate: "2008-06-13", director: "Louis Leterrier", runtime: 112,
    synopsis: "Bruce Banner hunts a cure on the run while the army hunts the monster inside him.",
    initials: "TIH", imdbId: "tt0800080", imdbRating: 6.6,
    universe: "mcu", studio: STUDIO, franchise: "Hulk",
    characters: ["hulk"], villains: ["Abomination", "General Ross"],
  },
  {
    id: "iron-man-2", title: "Iron Man 2", year: 2010, phase: 1, chronoOrder: 4,
    releaseDate: "2010-05-07", director: "Jon Favreau", runtime: 124,
    synopsis: "Tony Stark is dying of his own power source as a Russian physicist comes to collect a debt.",
    initials: "IM2", imdbId: "tt1228705", imdbRating: 6.9,
    universe: "mcu", studio: STUDIO, franchise: "Iron Man",
    characters: ["iron-man"], villains: ["Whiplash", "Justin Hammer"],
  },
  {
    id: "thor", title: "Thor", year: 2011, phase: 1, chronoOrder: 6,
    releaseDate: "2011-05-06", director: "Kenneth Branagh", runtime: 115,
    synopsis: "An arrogant Asgardian prince is stripped of his hammer and exiled to Earth to earn it back.",
    initials: "TH", imdbId: "tt0800369", imdbRating: 7.0,
    universe: "mcu", studio: STUDIO, franchise: "Thor",
    characters: ["thor"], villains: ["Loki", "Laufey"],
  },
  {
    id: "captain-america-the-first-avenger", title: "Captain America: The First Avenger", year: 2011, phase: 1, chronoOrder: 1,
    releaseDate: "2011-07-22", director: "Joe Johnston", runtime: 124,
    synopsis: "A frail volunteer becomes a super-soldier and takes on HYDRA in the Second World War.",
    initials: "CA", imdbId: "tt0458339", imdbRating: 6.9,
    universe: "mcu", studio: STUDIO, franchise: "Captain America",
    characters: ["captain-america"], villains: ["Red Skull", "Arnim Zola"],
  },
  {
    id: "the-avengers", title: "The Avengers", year: 2012, phase: 1, chronoOrder: 7,
    releaseDate: "2012-05-04", director: "Joss Whedon", runtime: 143,
    synopsis: "Earth's mightiest heroes are assembled to stop Loki's Chitauri invasion of New York.",
    initials: "AV", imdbId: "tt0848228", imdbRating: 8.0,
    universe: "mcu", studio: STUDIO, franchise: "Avengers",
    characters: ["iron-man", "captain-america", "thor", "hulk"], villains: ["Loki", "Thanos"],
  },

  // ── Phase Two ──────────────────────────────────────────────────────────────
  {
    id: "iron-man-3", title: "Iron Man 3", year: 2013, phase: 2, chronoOrder: 8,
    releaseDate: "2013-05-03", director: "Shane Black", runtime: 130,
    synopsis: "Stripped of his armoury and rattled by New York, Stark hunts a terrorist called the Mandarin.",
    initials: "IM3", imdbId: "tt1300854", imdbRating: 7.1,
    universe: "mcu", studio: STUDIO, franchise: "Iron Man",
    characters: ["iron-man"], villains: ["Aldrich Killian", "The Mandarin"],
  },
  {
    id: "thor-the-dark-world", title: "Thor: The Dark World", year: 2013, phase: 2, chronoOrder: 9,
    releaseDate: "2013-11-08", director: "Alan Taylor", runtime: 112,
    synopsis: "Thor allies with Loki against Malekith, who would return the Nine Realms to darkness.",
    initials: "TDW", imdbId: "tt1981115", imdbRating: 6.8,
    universe: "mcu", studio: STUDIO, franchise: "Thor",
    characters: ["thor"], villains: ["Malekith", "Kurse"],
  },
  {
    id: "captain-america-the-winter-soldier", title: "Captain America: The Winter Soldier", year: 2014, phase: 2, chronoOrder: 10,
    releaseDate: "2014-04-04", director: "Anthony & Joe Russo", runtime: 136,
    synopsis: "Rogers uncovers HYDRA inside S.H.I.E.L.D. and faces a ghost from his own past.",
    initials: "TWS", imdbId: "tt1843866", imdbRating: 7.7,
    universe: "mcu", studio: STUDIO, franchise: "Captain America",
    characters: ["captain-america"], villains: ["Winter Soldier", "Alexander Pierce"],
  },
  {
    id: "guardians-of-the-galaxy", title: "Guardians of the Galaxy", year: 2014, phase: 2, chronoOrder: 11,
    releaseDate: "2014-08-01", director: "James Gunn", runtime: 121,
    synopsis: "A band of cosmic criminals reluctantly bands together over a stolen orb worth the galaxy.",
    initials: "GG", imdbId: "tt2015381", imdbRating: 8.0,
    universe: "mcu", studio: STUDIO, franchise: "Guardians of the Galaxy",
    characters: ["guardians"], villains: ["Ronan the Accuser", "Nebula"],
  },
  {
    id: "avengers-age-of-ultron", title: "Avengers: Age of Ultron", year: 2015, phase: 2, chronoOrder: 13,
    releaseDate: "2015-05-01", director: "Joss Whedon", runtime: 141,
    synopsis: "Stark's peacekeeping AI decides that peace on Earth requires no Earth at all.",
    initials: "AOU", imdbId: "tt2395427", imdbRating: 7.3,
    universe: "mcu", studio: STUDIO, franchise: "Avengers",
    characters: ["iron-man", "captain-america", "thor", "hulk"], villains: ["Ultron"],
  },
  {
    id: "ant-man", title: "Ant-Man", year: 2015, phase: 2, chronoOrder: 14,
    releaseDate: "2015-07-17", director: "Peyton Reed", runtime: 117,
    synopsis: "A cat burglar inherits a shrinking suit and pulls a heist to keep the technology buried.",
    initials: "AM", imdbId: "tt0478970", imdbRating: 7.3,
    universe: "mcu", studio: STUDIO, franchise: "Ant-Man",
    characters: ["ant-man"], villains: ["Yellowjacket"],
  },

  // ── Phase Three ────────────────────────────────────────────────────────────
  {
    id: "captain-america-civil-war", title: "Captain America: Civil War", year: 2016, phase: 3, chronoOrder: 15,
    releaseDate: "2016-05-06", director: "Anthony & Joe Russo", runtime: 147,
    synopsis: "Government oversight splits the Avengers into two camps, and the split turns personal.",
    initials: "CW", imdbId: "tt3498820", imdbRating: 7.8,
    universe: "mcu", studio: STUDIO, franchise: "Captain America",
    characters: ["captain-america", "iron-man", "spider-man", "black-panther", "ant-man"], villains: ["Helmut Zemo"],
  },
  {
    id: "doctor-strange", title: "Doctor Strange", year: 2016, phase: 3, chronoOrder: 19,
    releaseDate: "2016-11-04", director: "Scott Derrickson", runtime: 115,
    synopsis: "A ruined surgeon seeks healing in Kamar-Taj and finds the mystic arts instead.",
    initials: "DS", imdbId: "tt1211837", imdbRating: 7.5,
    universe: "mcu", studio: STUDIO, franchise: "Doctor Strange",
    characters: ["doctor-strange"], villains: ["Kaecilius", "Dormammu"],
  },
  {
    id: "guardians-of-the-galaxy-vol-2", title: "Guardians of the Galaxy Vol. 2", year: 2017, phase: 3, chronoOrder: 12,
    releaseDate: "2017-05-05", director: "James Gunn", runtime: 136,
    synopsis: "Peter Quill meets his father and learns what a living planet wants from a son.",
    initials: "GG2", imdbId: "tt3896198", imdbRating: 7.6,
    universe: "mcu", studio: STUDIO, franchise: "Guardians of the Galaxy",
    characters: ["guardians"], villains: ["Ego", "Ayesha"],
  },
  {
    id: "spider-man-homecoming", title: "Spider-Man: Homecoming", year: 2017, phase: 3, chronoOrder: 18,
    releaseDate: "2017-07-07", director: "Jon Watts", runtime: 133,
    synopsis: "Peter Parker juggles high school and an arms dealer flying on salvaged Chitauri tech.",
    initials: "SMH", imdbId: "tt2250912", imdbRating: 7.4,
    universe: "mcu", studio: STUDIO, franchise: "Spider-Man (MCU)",
    characters: ["spider-man", "iron-man"], villains: ["Vulture", "Shocker"],
  },
  {
    id: "thor-ragnarok", title: "Thor: Ragnarok", year: 2017, phase: 3, chronoOrder: 20,
    releaseDate: "2017-11-03", director: "Taika Waititi", runtime: 130,
    synopsis: "Hammerless and marooned on Sakaar, Thor must escape a gladiator pit to stop Hela.",
    initials: "RAG", imdbId: "tt3501632", imdbRating: 7.9,
    universe: "mcu", studio: STUDIO, franchise: "Thor",
    characters: ["thor", "hulk"], villains: ["Hela", "Grandmaster"],
  },
  {
    id: "black-panther", title: "Black Panther", year: 2018, phase: 3, chronoOrder: 17,
    releaseDate: "2018-02-16", director: "Ryan Coogler", runtime: 134,
    synopsis: "T'Challa takes Wakanda's throne and is challenged by an exile with a rightful claim.",
    initials: "BP", imdbId: "tt1825683", imdbRating: 7.3,
    universe: "mcu", studio: STUDIO, franchise: "Black Panther",
    characters: ["black-panther"], villains: ["Killmonger", "Ulysses Klaue"],
  },
  {
    id: "avengers-infinity-war", title: "Avengers: Infinity War", year: 2018, phase: 3, chronoOrder: 22,
    releaseDate: "2018-04-27", director: "Anthony & Joe Russo", runtime: 149,
    synopsis: "Thanos comes for the Infinity Stones, and every hero in the galaxy is too late.",
    initials: "IW", imdbId: "tt4154756", imdbRating: 8.4,
    universe: "mcu", studio: STUDIO, franchise: "Avengers",
    characters: ["iron-man", "captain-america", "thor", "hulk", "doctor-strange", "spider-man", "guardians", "black-panther"],
    villains: ["Thanos", "Black Order"],
  },
  {
    id: "ant-man-and-the-wasp", title: "Ant-Man and the Wasp", year: 2018, phase: 3, chronoOrder: 21,
    releaseDate: "2018-07-06", director: "Peyton Reed", runtime: 118,
    synopsis: "Scott Lang and Hope van Dyne race to pull Janet out of the Quantum Realm.",
    initials: "AMW", imdbId: "tt5095030", imdbRating: 7.0,
    universe: "mcu", studio: STUDIO, franchise: "Ant-Man",
    characters: ["ant-man"], villains: ["Ghost", "Sonny Burch"],
  },
  {
    id: "captain-marvel", title: "Captain Marvel", year: 2019, phase: 3, chronoOrder: 2,
    releaseDate: "2019-03-08", director: "Anna Boden & Ryan Fleck", runtime: 123,
    synopsis: "A Kree soldier crash-lands in 1995 and recovers the human life that was taken from her.",
    initials: "CM", imdbId: "tt4154664", imdbRating: 6.8,
    universe: "mcu", studio: STUDIO, franchise: "Captain Marvel",
    characters: ["captain-marvel"], villains: ["Yon-Rogg", "Supreme Intelligence"],
  },
  {
    id: "avengers-endgame", title: "Avengers: Endgame", year: 2019, phase: 3, chronoOrder: 23,
    releaseDate: "2019-04-26", director: "Anthony & Joe Russo", runtime: 181,
    synopsis: "The survivors of the Snap gamble on a time heist to undo five years of loss.",
    initials: "EG", imdbId: "tt4154796", imdbRating: 8.4,
    universe: "mcu", studio: STUDIO, franchise: "Avengers",
    characters: ["iron-man", "captain-america", "thor", "hulk", "doctor-strange", "spider-man", "guardians", "black-panther", "ant-man", "captain-marvel"],
    villains: ["Thanos"],
  },
  {
    id: "spider-man-far-from-home", title: "Spider-Man: Far From Home", year: 2019, phase: 3, chronoOrder: 26,
    releaseDate: "2019-07-02", director: "Jon Watts", runtime: 129,
    synopsis: "A European school trip goes sideways when a man claiming to be from another Earth arrives.",
    initials: "FFH", imdbId: "tt6320628", imdbRating: 7.4,
    universe: "mcu", studio: STUDIO, franchise: "Spider-Man (MCU)",
    characters: ["spider-man"], villains: ["Mysterio"],
  },

  // ── Phase Four ─────────────────────────────────────────────────────────────
  {
    id: "black-widow", title: "Black Widow", year: 2021, phase: 4, chronoOrder: 16,
    releaseDate: "2021-07-09", director: "Cate Shortland", runtime: 134,
    synopsis: "Natasha Romanoff reunites with her fake family to burn down the Red Room for good.",
    initials: "BW", imdbId: "tt3480822", imdbRating: 6.7,
    universe: "mcu", studio: STUDIO, franchise: "Black Widow",
    characters: [], villains: ["Taskmaster", "Dreykov"],
  },
  {
    id: "shang-chi-and-the-legend-of-the-ten-rings", title: "Shang-Chi and the Legend of the Ten Rings", year: 2021, phase: 4, chronoOrder: 24,
    releaseDate: "2021-09-03", director: "Destin Daniel Cretton", runtime: 132,
    synopsis: "A San Francisco valet is dragged back into his father's thousand-year-old empire.",
    initials: "SC", imdbId: "tt9376612", imdbRating: 7.4,
    universe: "mcu", studio: STUDIO, franchise: "Shang-Chi",
    characters: [], villains: ["Wenwu", "The Dweller-in-Darkness"],
  },
  {
    id: "eternals", title: "Eternals", year: 2021, phase: 4, chronoOrder: 25,
    releaseDate: "2021-11-05", director: "Chloé Zhao", runtime: 156,
    synopsis: "Immortals who watched humanity for millennia must finally choose a side.",
    initials: "ET", imdbId: "tt9032400", imdbRating: 6.3,
    universe: "mcu", studio: STUDIO, franchise: "Eternals",
    characters: [], villains: ["Kro", "Arishem"],
  },
  {
    id: "spider-man-no-way-home", title: "Spider-Man: No Way Home", year: 2021, phase: 4, chronoOrder: 27,
    releaseDate: "2021-12-17", director: "Jon Watts", runtime: 148,
    synopsis: "A botched memory spell cracks the multiverse open and lets old enemies through.",
    initials: "NWH", imdbId: "tt10872600", imdbRating: 8.2,
    universe: "mcu", studio: STUDIO, franchise: "Spider-Man (MCU)",
    characters: ["spider-man", "doctor-strange"], villains: ["Green Goblin", "Doctor Octopus", "Electro", "Sandman", "The Lizard"],
  },
  {
    id: "doctor-strange-in-the-multiverse-of-madness", title: "Doctor Strange in the Multiverse of Madness", year: 2022, phase: 4, chronoOrder: 28,
    releaseDate: "2022-05-06", director: "Sam Raimi", runtime: 126,
    synopsis: "Strange protects a girl who can punch holes between realities from a grieving witch.",
    initials: "MOM", imdbId: "tt9419884", imdbRating: 6.9,
    universe: "mcu", studio: STUDIO, franchise: "Doctor Strange",
    characters: ["doctor-strange"], villains: ["Scarlet Witch", "Gargantos"],
  },
  {
    id: "thor-love-and-thunder", title: "Thor: Love and Thunder", year: 2022, phase: 4, chronoOrder: 29,
    releaseDate: "2022-07-08", director: "Taika Waititi", runtime: 118,
    synopsis: "Thor's retirement ends when a god butcher starts working his way down the pantheon.",
    initials: "LT", imdbId: "tt10648342", imdbRating: 6.2,
    universe: "mcu", studio: STUDIO, franchise: "Thor",
    characters: ["thor", "guardians"], villains: ["Gorr the God Butcher", "Zeus"],
  },
  {
    id: "black-panther-wakanda-forever", title: "Black Panther: Wakanda Forever", year: 2022, phase: 4, chronoOrder: 30,
    releaseDate: "2022-11-11", director: "Ryan Coogler", runtime: 161,
    synopsis: "A grieving Wakanda defends its throne and its vibranium against the undersea kingdom of Talokan.",
    initials: "WF", imdbId: "tt9114286", imdbRating: 6.7,
    universe: "mcu", studio: STUDIO, franchise: "Black Panther",
    characters: ["black-panther"], villains: ["Namor", "Attuma"],
  },

  // ── Phase Five ─────────────────────────────────────────────────────────────
  {
    id: "ant-man-and-the-wasp-quantumania", title: "Ant-Man and the Wasp: Quantumania", year: 2023, phase: 5, chronoOrder: 31,
    releaseDate: "2023-02-17", director: "Peyton Reed", runtime: 124,
    synopsis: "The Lang family falls into the Quantum Realm and meets the exile who rules it.",
    initials: "QM", imdbId: "tt10954600", imdbRating: 6.1,
    universe: "mcu", studio: STUDIO, franchise: "Ant-Man",
    characters: ["ant-man"], villains: ["Kang the Conqueror", "MODOK"],
  },
  {
    id: "guardians-of-the-galaxy-vol-3", title: "Guardians of the Galaxy Vol. 3", year: 2023, phase: 5, chronoOrder: 32,
    releaseDate: "2023-05-05", director: "James Gunn", runtime: 150,
    synopsis: "The Guardians risk everything to save Rocket and confront the man who made him.",
    initials: "GG3", imdbId: "tt6791350", imdbRating: 7.9,
    universe: "mcu", studio: STUDIO, franchise: "Guardians of the Galaxy",
    characters: ["guardians"], villains: ["The High Evolutionary", "Adam Warlock"],
  },
  {
    id: "the-marvels", title: "The Marvels", year: 2023, phase: 5, chronoOrder: 33,
    releaseDate: "2023-11-10", director: "Nia DaCosta", runtime: 105,
    synopsis: "Three heroes swap places every time they use their powers, and have to learn to fight as one.",
    initials: "TM", imdbId: "tt10676048", imdbRating: 5.5,
    universe: "mcu", studio: STUDIO, franchise: "Captain Marvel",
    characters: ["captain-marvel"], villains: ["Dar-Benn"],
  },
  {
    id: "deadpool-and-wolverine", title: "Deadpool & Wolverine", year: 2024, phase: 5, chronoOrder: 34,
    releaseDate: "2024-07-26", director: "Shawn Levy", runtime: 128,
    synopsis: "Wade Wilson is conscripted by the TVA and drags the worst possible Wolverine along.",
    initials: "DW", imdbId: "tt6263850", imdbRating: 7.7,
    universe: "mcu", studio: STUDIO, franchise: "Deadpool",
    characters: ["deadpool", "wolverine"], villains: ["Cassandra Nova", "Mr. Paradox"],
  },
  {
    id: "captain-america-brave-new-world", title: "Captain America: Brave New World", year: 2025, phase: 5, chronoOrder: 35,
    releaseDate: "2025-02-14", director: "Julius Onah", runtime: 118,
    synopsis: "Sam Wilson's first mission as Captain America collides with a new President's agenda.",
    initials: "BNW", imdbId: "tt14513804", imdbRating: 5.6,
    universe: "mcu", studio: STUDIO, franchise: "Captain America",
    characters: ["captain-america"], villains: ["Red Hulk", "The Leader"],
  },
  {
    id: "thunderbolts", title: "Thunderbolts*", year: 2025, phase: 5, chronoOrder: 36,
    releaseDate: "2025-05-02", director: "Jake Schreier", runtime: 127,
    synopsis: "A group of disposable antiheroes is set up to die and decides not to oblige.",
    initials: "TB", imdbId: "tt20969586", imdbRating: 7.1,
    universe: "mcu", studio: STUDIO, franchise: "Thunderbolts",
    characters: [], villains: ["The Sentry / Void", "Valentina Allegra de Fontaine"],
  },

  // ── Phase Six ──────────────────────────────────────────────────────────────
  {
    id: "the-fantastic-four-first-steps", title: "The Fantastic Four: First Steps", year: 2025, phase: 6, chronoOrder: 37,
    releaseDate: "2025-07-25", director: "Matt Shakman", runtime: 115,
    synopsis: "A retro-futurist first family defends their Earth from a world-eater and his herald.",
    initials: "F4", imdbId: "tt10676052", imdbRating: 6.8,
    universe: "mcu", studio: STUDIO, franchise: "Fantastic Four (MCU)",
    characters: ["fantastic-four"], villains: ["Galactus", "Silver Surfer"],
  },
  {
    id: "spider-man-brand-new-day", title: "Spider-Man: Brand New Day", year: 2026, phase: 6, chronoOrder: 38,
    releaseDate: "2026-07-31", director: "Destin Daniel Cretton", runtime: null,
    synopsis: "A Peter Parker nobody remembers starts over from nothing in a changed New York.",
    initials: "BND", imdbId: "tt22084616", imdbRating: null,
    universe: "mcu", studio: STUDIO, franchise: "Spider-Man (MCU)",
    characters: ["spider-man"], villains: ["Scorpion", "Hulk"],
  },
  {
    id: "avengers-doomsday", title: "Avengers: Doomsday", year: 2026, phase: 6, chronoOrder: 39,
    releaseDate: "2026-12-18", director: "Anthony & Joe Russo", runtime: null,
    synopsis: "Heroes from across the multiverse are drawn together against Doctor Doom.",
    initials: "AD", imdbId: "tt21357150", imdbRating: null,
    universe: "mcu", studio: STUDIO, franchise: "Avengers",
    characters: ["fantastic-four", "thor", "captain-america"], villains: ["Doctor Doom"],
  },
  {
    id: "avengers-secret-wars", title: "Avengers: Secret Wars", year: 2027, phase: 6, chronoOrder: 40,
    releaseDate: "2027-12-17", director: "Anthony & Joe Russo", runtime: null,
    synopsis: "The final incursion collapses the multiverse into one battleworld.",
    initials: "SW", imdbId: "tt21361444", imdbRating: null,
    universe: "mcu", studio: STUDIO, franchise: "Avengers",
    characters: [], villains: ["Doctor Doom"],
  },
];
